export const EXPERIENCE_KEYS = {
  TITLE: 'title',
  COMPANY_NAME: 'companyName',
  LOCATION: 'location',
  START_DATE: 'startDate',
  END_DATE: 'endDate',
  INDUSTRY: 'industry',
  DESCRIPTION: 'description',
  EMPLOYMENT_TYPE: 'employmentType',
};

export const EMPLOYMENT_TYPES = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  FREELANCE: 'FREELANCE',
  CONTRACT: 'CONTRACT',
  INTERNSHIP: 'INTERNSHIP',
  APPRENTICENSHIP: 'APPRENTICENSHIP',
  SEASONAL: 'SEASONAL',
};
