const DASHBOARD_TEXTS = {
  INTROS_PAGE_TITLE: {
    es: 'Introducciones',
  },
  EXPERIENCES_PAGE_TITLE: {
    es: 'Experiencia',
  },
  SKILLS_PAGE_TITLE: {
    es: 'Habilidades',
  },
  PROJECTS_PAGE_TITLE: {
    es: 'Proyectos',
  },
  EDUCATIONS_PAGE_TITLE: {
    es: 'Educación',
  },
  CONTACTS_PAGE_TITLE: {
    es: 'Contacto',
  },
  APIKEYS_PAGE_TITLE: { es: 'Apikeys' },
  ADD_INTRO_DIALOG_TITLE: {
    es: 'Agregar introducción',
  },
  INTRO_FIRST_NAME_LABEL: {
    es: 'Nombre',
  },
  INTRO_FORM_FIRST_NAME_PLACEHOLDER: {
    es: 'Escribí tu nombre',
  },
  INTRO_LAST_NAME_LABEL: {
    es: 'Apellido',
  },
  INTRO_FORM_LAST_NAME_PLACEHOLDER: {
    es: 'Escribí tu apellido',
  },
  INTRO_HEAD_LINE_LABEL: {
    es: 'Titular',
  },
  INTRO_FORM_HEAD_LINE_PLACEHOLDER: {
    es: 'Escribí tu titular',
  },
  INTRO_BIRTHDAY_LABEL: {
    es: 'Fecha de nacimiento',
  },
  INTRO_FORM_BIRTHDARY_PLACEHOLDER: {
    es: 'Escribí tu fecha de nacimiento',
  },
  INTRO_ABOUT_LABEL: {
    es: 'Sobre mi',
  },
  INTRO_FORM_ABOUT_PLACEHOLDER: {
    es: 'Escribí algo sobre vos',
  },
  MORE_INFO_INTRO_DIALOG_TITLE: {
    es: 'Ver introducción',
  },
  EDIT_INTRO_DIALOG_TITLE: {
    es: 'Editar introducción',
  },
  DELETE_INTRO_DIALOG_TITLE: {
    es: 'Eliminar introducción',
  },
  DELETE_INTRO_DIALOG_DESCRIPTION: {
    es: '¿Estas seguro de que deseas eliminar esta introducción?',
  },
  DELETE_ALL_INTROS_DIALOG_DESCRIPTION: {
    es: '¿Estas seguro de que deseas eliminar todas las introducciones?',
  },
  EXPERIENCE_TITLE_LABEL: { es: 'Título' },
  EXPERIENCE_COMPANY_NAME_LABEL: { es: 'Nombre de la empresa' },
  EXPERIENCE_LOCATION_LABEL: { es: 'Ubicación' },
  EXPERIENCE_START_DATE_LABEL: { es: 'Fecha de inicio' },
  EXPERIENCE_END_DATE_LABEL: { es: 'Fecha de finalización' },
  EXPERIENCE_INDUSTRY_LABEL: { es: 'Industria' },
  EXPERIENCE_DESCRIPTION_LABEL: { es: 'Descripción' },
  EXPERIENCE_EMPLOYMENT_TYPE_LABEL: { es: 'Tipo de empleo' },
  DELETE_EXPERIENCE_DIALOG_TITLE: { es: 'Eliminar experiencia' },
  ADD_EXPERIENCE_DIALOG_TITLE: { es: 'Agregar experiencia' },
  DELETE_ALL_EXPERIENCES_DIALOG_DESCRIPTION: {
    es: '¿Estas seguro de que deseas eliminar todas las experiencias?',
  },
  DELETE_EXPERIENCE_DIALOG_DESCRIPTION: {
    es: '¿Estas seguro de que deseas eliminar esta experiencia?',
  },
  EDIT_EXPERIENCE_DIALOG_TITLE: { es: 'Editar experiencia' },
  MORE_INFO_EXPERIENCE_DIALOG_TITLE: { es: 'Ver experiencia' },
  EXPERIENCE_FORM_TITLE_PLACEHOLDER: { es: 'Escribí el título' },
  EXPERIENCE_FORM_COMPANY_NAME_PLACEHOLDER: {
    es: 'Escribí el nombre de la empresa',
  },
  EXPERIENCE_FORM_LOCATION_PLACEHOLDER: { es: 'Escribí la ubicación' },
  EXPERIENCE_FORM_START_DATE_PLACEHOLDER: { es: 'Escribí la fecha de inicio' },
  EXPERIENCE_FORM_END_DATE_PLACEHOLDER: {
    es: 'Escribí la fecha de finalización',
  },
  EXPERIENCE_FORM_INDUSTRY_PLACEHOLDER: { es: 'Escribí la industria' },
  EXPERIENCE_FORM_DESCRIPTION_PLACEHOLDER: { es: 'Escribí la descripción' },
  EXPERIENCE_FORM_EMPLOYMENT_TYPE_PLACEHOLDER: {
    es: 'Elegí el tipo de empleo',
  },
  EXPERIENCE_EMPLOYMENT_TYPE_FULL_TIME_LABEL: { es: 'Jornada completa' },
  EXPERIENCE_EMPLOYMENT_TYPE_PART_TIME_LABEL: { es: 'Jornada parcial' },
  EXPERIENCE_EMPLOYMENT_TYPE_SELF_EMPLOYED_LABEL: { es: 'Autónomo' },
  EXPERIENCE_EMPLOYMENT_TYPE_FREELANCE_LABEL: {
    es: 'Profesional independiente',
  },
  EXPERIENCE_EMPLOYMENT_TYPE_CONTRACT_LABEL: { es: 'Contrato temporal' },
  EXPERIENCE_EMPLOYMENT_TYPE_INTERNSHIP_LABEL: { es: 'Contrato de prácticas' },
  EXPERIENCE_EMPLOYMENT_TYPE_APPRENTICENSHIP_LABEL: {
    es: 'Contrato de formación',
  },
  EXPERIENCE_EMPLOYMENT_TYPE_SEASONAL_LABEL: { es: 'Seasonal' },
  PROJECT_NAME_LABEL: { es: 'Nombre' },
  PROJECT_DESCRIPTION_LABEL: { es: 'Descripción' },
  PROJECT_START_DATE_LABEL: { es: 'Fecha de inicio' },
  PROJECT_END_DATE_LABEL: { es: 'Fecha de finalización' },
  PROJECT_URL_LABEL: { es: 'Url' },
  PROJECT_EDUCATION_LABEL: { es: 'Educación' },
  PROJECT_EXPERIENCE_LABEL: { es: 'Experiencia' },
  PROJECT_FORM_EDUCATION_PLACEHOLDER: { es: 'Elegí la educación asociada' },
  PROJECT_FORM_EXPERIENCE_PLACEHOLDER: { es: 'Elegí la experiencia asociada' },
  ADD_PROJECT_DIALOG_TITLE: { es: 'Agregar proyecto' },
  DELETE_ALL_PROJECTS_DIALOG_DESCRIPTION: {
    es: '¿Estas seguro de que deseas eliminar todos los proyectos?',
  },
  DELETE_PROJECT_DIALOG_TITLE: { es: 'Eliminar proyecto' },
  DELETE_PROJECT_DIALOG_DESCRIPTION: {
    es: '¿Estas seguro de que deseas eliminar este proyecto?',
  },
  EDIT_PROJECT_DIALOG_TITLE: { es: 'Editar proyecto' },
  PROJECT_FORM_NAME_PLACEHOLDER: { es: 'Escribí el nombre' },
  PROJECT_FORM_URL_PLACEHOLDER: { es: 'Escribí la url' },
  PROJECT_FORM_DESCRIPTION_PLACEHOLDER: { es: 'Escribí la descripción' },
  PROJECT_FORM_START_DATE_PLACEHOLDER: { es: 'Escribí la fecha de inicio' },
  PROJECT_FORM_END_DATE_PLACEHOLDER: { es: 'Escribí la fecha de finalización' },
  SKILL_NAME_LABEL: { es: 'Nombre' },
  SKILL_FORM_NAME_PLACEHOLDER: { es: 'Escribí el nombre de la habilidad' },
  EDUCATION_SCHOOL_LABEL: { es: 'Institución educativa' },
  EDUCATION_FORM_SCHOOL_PLACEHOLDER: { es: 'Escribí la institución educativa' },
  EDUCATION_DEGREE_LABEL: { es: 'Título' },
  EDUCATION_FORM_DEGREE_PLACEHOLDER: { es: 'Escribí el título' },
  EDUCATION_FIELD_OF_STUDY_LABEL: { es: 'Campo de estudio' },
  EDUCATION_FORM_FIELD_OF_STUDY_PLACEHOLDER: {
    es: 'Escribí el campo de estudio',
  },
  EDUCATION_START_DATE_LABEL: { es: 'Fecha de inicio' },
  EDUCATION_FORM_START_DATE_PLACEHOLDER: { es: 'Escribí la fecha de inicio' },
  EDUCATION_END_DATE_LABEL: { es: 'Fecha de finalización' },
  EDUCATION_FORM_END_DATE_PLACEHOLDER: {
    es: 'Escribí la fecha de finalización',
  },
  EDUCATION_GRADE_LABEL: { es: 'Calificación' },
  EDUCATION_FORM_GRADE_PLACEHOLDER: { es: 'Escribí la calificación' },
  EDUCATION_ACTIVITIES_LABEL: { es: 'Actividades' },
  EDUCATION_FORM_ACTIVITIES_PLACEHOLDER: { es: 'Escribí las actividades' },
  EDUCATION_DESCRIPTION_LABEL: { es: 'Descripción' },
  EDUCATION_FORM_DESCRIPTION_PLACEHOLDER: { es: 'Escribí la descripción' },
  CONTACT_TITLE_LABEL: { es: 'Título' },
  CONTACT_FORM_TITLE_PLACEHOLDER: { es: 'Escribí el título' },
  CONTACT_LINKEDIN_LABEL: { es: 'Linkedin' },
  CONTACT_FORM_LINKEDIN_PLACEHOLDER: { es: 'Ingresa la URL de tu perfil' },
  CONTACT_FACEBOOK_LABEL: { es: 'Facebook' },
  CONTACT_FORM_FACEBOOK_PLACEHOLDER: { es: 'Ingresa la URL de tu perfil' },
  CONTACT_TWITTER_LABEL: { es: 'Twitter' },
  CONTACT_FORM_TWITTER_PLACEHOLDER: { es: 'Ingresa la URL de tu perfil' },
  CONTACT_EMAIL_LABEL: { es: 'Correo electrónico' },
  CONTACT_FORM_EMAIL_PLACEHOLDER: { es: 'Ingresá tu correo electrónico' },
  CONTACT_PHONE_LABEL: { es: 'Teléfono' },
  CONTACT_FORM_PHONE_PLACEHOLDER: { es: 'Ingresá tu teléfono' },
  CONTACT_MOBILE_PHONE_LABEL: { es: 'Teléfono celular' },
  CONTACT_FORM_MOBILE_PHONE_PLACEHOLDER: { es: 'Ingresá tu teléfono celular' },
  CONTACT_ADDRESS_LABEL: { es: 'Dirección' },
  CONTACT_FORM_ADDRESS_PLACEHOLDER: { es: 'Ingresá tu dirección' },
  CONTACT_GITHUB_LABEL: { es: 'Github' },
  CONTACT_FORM_GITHUB_PLACEHOLDER: { es: 'Ingresa la URL de tu perfil' },
  CONTACT_COUNTRY_LABEL: { es: 'País' },
  CONTACT_FORM_COUNTRY_PLACEHOLDER: { es: 'Ingresá tu país' },
  CONTACT_POSTAL_CODE_LABEL: { es: 'Código postal' },
  CONTACT_FORM_POSTAL_CODE_PLACEHOLDER: { es: 'Ingresá tu código postal' },
  CONTACT_CITY_LABEL: { es: 'Ciudad' },
  CONTACT_FORM_CITY_PLACEHOLDER: { es: 'Ingresá tu ciudad' },
  CONTACT_WEBSITE_LABEL: { es: 'Sitio web' },
  CONTACT_FORM_WEBSITE_PLACEHOLDER: { es: 'Ingresa la URL de tu sitio web' },
  RESUME_TITLE_LABEL: { es: 'Título' },
  RESUME_INTRO_LABEL: { es: 'Introducción' },
  RESUME_CONTACT_LABEL: { es: 'Contacto' },
  RESUME_EXPERIENCES_LABEL: { es: 'Experiencias' },
  SKILLS_LABEL: { es: 'Habilidades' },
  RESUME_EDUCATIONS_LABEL: { es: 'Educaciones' },
  RESUME_PROJECTS_LABEL: { es: 'Proyectos' },
  RESUME_FORM_TITLE_PLACEHOLDER: { es: 'Ingresá el título' },
  RESUME_FORM_INTRO_PLACEHOLDER: { es: 'Elegí una introducción' },
  RESUME_FORM_CONTACT_PLACEHOLDER: { es: 'Elegí tu información de contacto' },
  RESUME_FORM_EXPERIENCES_PLACEHOLDER: {
    es: 'Elegí las experiencias asociadas',
  },
  FORM_SKILLS_PLACEHOLDER: { es: 'Elegí las habilidades asociadas' },
  RESUME_FORM_EDUCATIONS_PLACEHOLDER: { es: 'Elegí las educaciones asociadas' },
  RESUME_FORM_PROJECTS_PLACEHOLDER: { es: 'Elegí los proyectos asociados' },
  RESUMES_PAGE_TITLE: { es: 'Currículums' },
  APIKEY_TITLE_LABEL: { es: 'Título' },
  APIKEY_FORM_TITLE_PLACEHOLDER: { es: 'Escribí el título' },
  APIKEY_RESUME_LABEL: { es: 'Curriculum' },
  APIKEY_FORM_RESUME_PLACEHOLDER: { es: 'Elegí un curriculum' },
  APIKEY_ID_LABEL: { es: 'Clave apikey' },
  PROJECT_IMG_SRC_LABEL: { es: 'Imagen' },
  PROJECT_FORM_IMG_SRC_PLACEHOLDER: { es: 'Ingresá la URL de la imagen' },
  EXPERIENCE_IMG_SRC_LABEL: { es: 'Imagen' },
  EXPERIENCE_FORM_IMG_SRC_PLACEHOLDER: { es: 'Ingresá la URL de la imagen' },
  EDUCATION_IMG_SRC_LABEL: { es: 'Imagen' },
  EDUCATION_FORM_IMG_SRC_PLACEHOLDER: { es: 'Ingresá la URL de la imagen' },
  INTRO_IMG_SRC_LABEL: { es: 'Imagen' },
  INTRO_FORM_IMG_SRC_PLACEHOLDER: { es: 'Ingresá la URL de la imagen' },
  SKILL_IMG_SRC_LABEL: { es: 'Imagen' },
  SKILL_FORM_IMG_SRC_PLACEHOLDER: { es: 'Ingresá la URL de la imagen' },
};

export default DASHBOARD_TEXTS;
